apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-tools-observability
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: infra-src
    - name: infra-ns
  path: ./infra/observability
  wait: true
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  sourceRef:
    kind: GitRepository
    name: flux-system
