apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-ns
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infra/ns
  dependsOn:
    - name: infra-src
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
