apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  labels:
    app.kubernetes.io/part-of: istio
spec:
  interval: 1h
  url: https://istio-release.storage.googleapis.com/charts
