apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway-main
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: gateway-main
  chart:
    spec:
      version: "${istio_version}"
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 10
  values:
    service:
      type: NodePort
      ports:
        - port: 10080
          targetPort: 10080
          nodePort: 32080
