apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: istio-operator
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 2.16.7
  valuesFrom:
    - kind: ConfigMap
      name: istio-values
