apiVersion: v1
data:
    token: ENC[AES256_GCM,data:hxUobWJeYsU0lUXx99Hn8quSSe56SNz7lM8BPWJPggz5+M0ol3n+7RBALCkMIAtfM62zEX7pAz6Kjnr1y9gRdA==,iv:LPAe00BBmUCUPotW9a38L2cMJ0V4HuX5V4LGKd9hxNk=,tag:us8sBS7j+bM7b4o+78tTuw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: telegram-token
sops:
    lastmodified: "2025-08-03T00:06:52Z"
    mac: ENC[AES256_GCM,data:22XlgPKdQ35HXlSGGOSlT0ZRBx7jp2vyVoMRewg/GqBwwCbPYRCdudlNVGzgA+8Ny2aYhWSbdCtnZcWUlWLL61zIQlTtUduDXxm0waqzd+efvF82svgdeP1mB3lvN8tfvF/o9eCeMHuONfhpMU9o4Z7Et8cYM5m/XaBueJs1Juo=,iv:eAiR1aSRtgfWIPXubeAQv53WRu3YUVqnEWzRRjmKUJU=,tag:xWTHRuu21wf6VUoiQZaNAQ==,type:str]
    pgp:
        - created_at: "2025-08-02T23:26:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----
            adasasd
            hQIMA7bTx4gPbMAdAQ/+OzOCEPSJWX0YxCZYWoQd4CyNGQVQ7SAcdg/3CDnsSrN3
            q3+rWnDp3Ey7/nDF0t+XUeSYQHBcXxqedeLKiMgHD4TMCmrQtyM+YeOBerrOawfr
            SwrDph8xgRu/ztI5TiEPYHtmPuSmj4sbfbGp1/xyeR4KaVlP/3NDOvijGaLVlaz6
            b1HGT7WW44Nrc2hhyuOCUrE7td5liGNz3nyzXKZ82NlnEthLA5HOgdoJrdJsxFtj
            XmY7pf08oUVmx8/22eCWQk57VihCJHJ68Uz1mthnQAeoVuSxDS099pj/HetPyY8z
            zGK6BHMAFRIFUYafW18k+qnQA3Y/u9df9+enGANdolPkpBBZxQvPiFC+YdKwcClo
            VcUnbkbjQJ8iCxU6ZvdQboV/j3gNeJTmBq/CTA5BfI02br9jWAHyY7Ccxcyi8OPc
            4FFHwusKOBs83WiyegRUONZWNi2jm2IpQv/CmmtkXY3z5lLb8uc/f0PDeCfLIxM6
            /c+wxSQdc1RfBt8wz9usg4peO4cmb/bsD+TuxM6TZliHsrydx0eSsD+Er2eEgaWx
            fDYXrqklHL4EXxJDXCy6zl5/8eOdWH8l1DYX5JdBJzjJPPBXjWWYkWTqS4zZBAmL
            +JxzKXvvbh8h9NdB3jBPx5ivrsomJGtiWsmsNEm4MyzUTFIs6ox9ZDEZOQ5ize3U
            aAEJAhA0S9M3zjrdI7uHc0ybfvqR3M7JHRlKT4sAAfLD6BE8WRfghAKJim+z1ATv
            aHqKvUjAjxQRDnQIRyy7lZMxql22baE94tHH5CQZTWDd4y9p/mzhPYsrxPzui3r1
            zijmE/ulTyVX
            =z3ZK
            -----END PGP MESSAGE-----
          fp: 6907FB322F0BB5BC2C85ED44D09F51571F519007
    encrypted_regex: ^(data)$
    version: 3.10.2
