apiVersion: v1
data:
    token: ENC[AES256_GCM,data:c9VdEj1zwqHBsY40/HrtocXP8ab4oztkLE21KyTQNcYayJ69MjreWM9d/TBbFhx5YM3OQnPEnbcudy1o,iv:Q3pS0vPH363SuIraDiIPlrxqXRsG05Xlvip8065mTQk=,tag:dYiuqFbI50xaejc9LbTB5w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: telegram-token
sops:
    lastmodified: "2025-08-02T23:26:54Z"
    mac: ENC[AES256_GCM,data:Y/yeN+MOw99GmaNwtLBw7Ppoh5iBitPmOR58Hu0bQLJWB3AbibQVEYdGa4lNCsEUeVgjvXCme3CzH27hstXxLi0ophMMfiRk0or5463Cv/oRQzunazVW3ufiHCebENX6h3L18N7a/o/JJa8AUn6M8G0UTZS84ezdI6cQDW3d26M=,iv:0STf4XkMO2fXeWKmmSaIppvqPP8fpcnhmNLj+UeylEU=,tag:dzHvk2/Hi0csRVbyDXc3RA==,type:str]
    pgp:
        - created_at: "2025-08-02T23:26:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA7bTx4gPbMAdAQ/+OzOCEPSJWX0YxCZYWoQd4CyNGQVQ7SAcdg/3CDnsSrN3
            q3+rWnDp3Ey7/nDF0t+XUeSYQHBcXxqedeLKiMgHD4TMCmrQtyM+YeOBerrOawfr
            SwrDph8xgRu/ztI5TiEPYHtmPuSmj4sbfbGp1/xyeR4KaVlP/3NDOvijGaLVlaz6
            b1HGT7WW44Nrc2hhyuOCUrE7td5liGNz3nyzXKZ82NlnEthLA5HOgdoJrdJsxFtj
            XmY7pf08oUVmx8/22eCWQk57VihCJHJ68Uz1mthnQAeoVuSxDS099pj/HetPyY8z
            zGK6BHMAFRIFUYafW18k+qnQA3Y/u9df9+enGANdolPkpBBZxQvPiFC+YdKwcClo
            VcUnbkbjQJ8iCxU6ZvdQboV/j3gNeJTmBq/CTA5BfI02br9jWAHyY7Ccxcyi8OPc
            4FFHwusKOBs83WiyegRUONZWNi2jm2IpQv/CmmtkXY3z5lLb8uc/f0PDeCfLIxM6
            /c+wxSQdc1RfBt8wz9usg4peO4cmb/bsD+TuxM6TZliHsrydx0eSsD+Er2eEgaWx
            fDYXrqklHL4EXxJDXCy6zl5/8eOdWH8l1DYX5JdBJzjJPPBXjWWYkWTqS4zZBAmL
            +JxzKXvvbh8h9NdB3jBPx5ivrsomJGtiWsmsNEm4MyzUTFIs6ox9ZDEZOQ5ize3U
            aAEJAhA0S9M3zjrdI7uHc0ybfvqR3M7JHRlKT4sAAfLD6BE8WRfghAKJim+z1ATv
            aHqKvUjAjxQRDnQIRyy7lZMxql22baE94tHH5CQZTWDd4y9p/mzhPYsrxPzui3r1
            zijmE/ulTyVX
            =z3ZK
            -----END PGP MESSAGE-----
          fp: 6907FB322F0BB5BC2C85ED44D09F51571F519007
    encrypted_regex: ^(data)$
    version: 3.10.2
