apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  releaseName: loki
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: 6.33.0
  valuesFrom:
    - kind: ConfigMap
      name: loki-values
  interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 10
