apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istiod
  dependsOn:
    - name: istio-base
  chart:
    spec:
      version: "${istio_version}"
      chart: istiod
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 10
  valuesFrom:
    - kind: ConfigMap
      name: istiod-values
